"""empty message

Revision ID: 29179e295aab
Revises: 
Create Date: 2019-06-28 17:46:25.311964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29179e295aab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=128), nullable=False),
    sa.Column('snumber', sa.String(length=64), nullable=False),
    sa.Column('buyTime', sa.DateTime(), nullable=True),
    sa.Column('sellTime', sa.DateTime(), nullable=True),
    sa.Column('shands', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_stock_sname'), 'stock', ['sname'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=32), nullable=False),
    sa.Column('upwd', sa.String(length=64), nullable=True),
    sa.Column('userTime', sa.DateTime(), nullable=True),
    sa.Column('vipTime', sa.DateTime(), nullable=True),
    sa.Column('avaMoney', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('stockMoney', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('amt', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_uname'), 'user', ['uname'], unique=True)
    op.create_table('user_stock',
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['stock.sid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('usid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stock')
    op.drop_index(op.f('ix_user_uname'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_stock_sname'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
